# Generated by Django 5.2.12 on 2026-06-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'base_manager_name': 'objects', 'ordering': ['-transaction_date', '-id']},
        ),
    ]
