# Generated by Django 5.2.12 on 2026-04-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_ensure_category_id_and_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
